services:
  db:
    image: mysql:8.0.42
    container_name: awesome_collect_db
    environment:
      MYSQL_DATABASE: awesome_collect
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_date:/var/lib/mysql

volumes:
  db_date: